### ISSUE TITLE
Programa fecha 

### ISSUE THREAD

**Issue by morasmich7** [Kartatz/SparkleC#10]
Boa tarde, ele começa a baixar normalmente os arquivos e coloca-los em pastas, porem quando chega no modulo 10 de 13 modulos que tem ele fecha e depois abro novamente ele verifica os que ja baixou e nao da prosseguimento. 
dentro desse modulo tem essa lampada que é um video como se fosse propaganda, sera que ele esta tentando ler esse video e esta dando algum erro e fecha? teria como você me ajudar amigo? 
![image](https://user-images.githubusercontent.com/120328411/206921086-4413fbdf-1047-4d5f-91a5-46494d09b016.png)

**Comment by morasmich7** [comment]
fiz um video mostrando como acontece, porem nao consigo enviar pois o mesmo tem 75mb e aqui so permite 10mb.

**Comment by Kartatz** [comment]
Execute o programa através do Power Shell e envie uma captura de tela do que aparece no final.

**Comment by morasmich7** [comment]
Obrigado irmão, fui pelo Power Shell e consegui baixar tudo. Muito obrigado pela ajuda!

**Comment by camilaamorims** [comment]
> Execute o programa através do Power Shell e envie uma captura de tela do que aparece no final.

como faz isso ? Não aparece "abrir com "
![Sem título](https://user-images.githubusercontent.com/127625982/224507511-564bead9-0d1f-410c-89e9-b9aa53e32857.png)
