### ISSUE TITLE
Caminho relativo ao invés de caminho fixo

### ISSUE THREAD

**Issue by marcelo-maciel** [Kartatz/SparkleC#11]
Oi @Kartatz!
Fiz o download de um curso pelo linux, estava rodando de dentro da pasta /home/MeuNome/blablabla/nomedocurso e assim por diante.
O sistema criou o arquivo nomedocurso.html e o arquivo nomedocurso.json.
Copiei a pasta toda para o windows e quando cliquei num link do HTML, ele me redirecionou para o arquivo como se estivesse ainda na máquina linux (/home/MeuNome/blablabla/nomedocurso), mas eu estava em d:/nomedocurso/

**Comment by Kartatz** [comment]
Essa característica é algo intencional.

Meu objetivo era possibilitar que a navegação entre os arquivos fosse possível independente de onde o arquivo HTML estivesse, seja no mesmo diretório onde os arquivos baixados estão ou em algum outro lugar.

Infelizmente, os caminhos relativos impossibilitam isso.
