### ISSUE TITLE
Opção/Configuração para escolha do tipo de caminho

### ISSUE THREAD

**Issue by marcelo-maciel** [Kartatz/SparkleC#14]
Oi @Kartatz! Seguindo nossa thread da issue #11, acredito que para a maior parte do utilizadores, até pensando em longo prazo, onde movemos os arquivos de um lugar para o outro, seria interessante dar a opção para o usuário selecionar ou configurar que tipo de caminho ele gostaria de utilizar, se fixo ou se relativo.

**Comment by Kartatz** [comment]
A árvore de objetos em HTML foi removida na última versão.

Como sua sugestão foi invalidada, estarei fechando este ticket.
