### ISSUE TITLE
Falha na tentativa de download de MP3

### ISSUE THREAD

**Issue by marcelo-maciel** [Kartatz/SparkleC#2]
Bom dia @Kartatz, antes de mais nada parabéns pelo excelente trabalho!
Estou fazendo o backup de um curso e sempre quando chega num arquivo com extensão .mp3 ele apresenta a mensagem "ocorreu uma falha inesperada".
Vi que na issue #1 houve problema com os tipos de arquivo e imaginei que meu problema poderia ter relação, consegue me ajudar?

**Comment by Kartatz** [comment]
No seu caso o problema é que o programa simplesmente não suporta esse tipo de mídia.

Durante meus testes não encontrei qualquer curso que possuísse arquivos de áudio anexados, então desconhecia essa possibilidade.

**Comment by marcelo-maciel** [comment]
Entendo. Neste caso pensa em fazer esta funcionalidade?
Caso não seja o objetivo, poderia fazer um "by pass" neste e nos demais arquivos não suportados?
Um log ao final dos arquivos não baixados seria legal também.

**Comment by Kartatz** [comment]
Você poderia testar a última snapshot do programa e verificar se isso resolve seu problema?

Você pode obtê-la através do GitHub Actions deste repositório.

**Comment by marcelo-maciel** [comment]
Funcionou perfeitamente @Kartatz, muito obrigado!
