### ISSUE TITLE
Erro de download de mídia 

### ISSUE THREAD

**Issue by Coogan085** [Kartatz/SparkleC#21]
![Screenshot_2023-01-08-00-57-58-656_com anydesk anydeskandroid](https://user-images.githubusercontent.com/118844585/211179996-5a602f16-1e2d-48df-abbc-23755668aa8f.jpg)
Ta dando esse erro

**Comment by flaprocha** [comment]
Relatei uma situação similar poucos minutos após sua postagem, confira no seguinte [link](https://github.com/Kartatz/SparkleC/issues/22).
