### ISSUE TITLE
Erro ao tentar executar

### ISSUE THREAD

**Issue by Navif77** [Kartatz/SparkleC#23]
![spc](https://user-images.githubusercontent.com/122526952/212040837-5919c3bb-d5f6-48bb-84cd-163f739a307d.png)

Ja tentei no windows 11 e 10, tentei pelo git, cmd e powershell e já testei a versão 0.2 e 0.3 em todos os ambientes também.

ffmepg instalado de maneira correta também
caminho da pasta curto(C:/e/bin)

Alguma idéia do que fazer?
Qualquer coisa também tenho um kali linux pra usar ou posso usar uma vm

**Comment by Kartatz** [comment]
O programa está dizendo que você não deve executá-lo como admistrador. Crie um usuário comum e execute-o por ele.
