### ISSUE TITLE
Erro durante o download.

### ISSUE THREAD

**Issue by runawaydevil** [Kartatz/SparkleC#24]
Estou fazendo o curso que aparecerá aí e é a primeira vez que uso o SpakleC. Quando o coloco para fazer download do curso, ele consegue baixar 2 módulos (o curso tem 16) e do nada para.
Veja a tela:
![image](https://user-images.githubusercontent.com/8763225/212380627-aff557ec-14f7-40b0-8fd3-a0e82175b4fd.png)
Alguém já passou por isso? Vi alguns camaradas aqui no fórum relatando erros que aparentemente eram do ffmpeg, mas eu sinceramente sou bem novo com esse tipo de coisa.

**Comment by runawaydevil** [comment]
**Atualização**

O erro aparentemente está aqui:
![image](https://user-images.githubusercontent.com/8763225/212384049-bbba2ad6-e6c1-4289-9570-a238de70fb06.png)
Se eu coloco em S o programa crasha alguns momentos após fazer o download, se eu coloco n, ele faz normalmente.

Obrigado de qualquer forma e mesmo assim caso haja uma solução... estou aqui.

**Comment by Kartatz** [comment]
Leia a issue #9.

**Comment by runawaydevil** [comment]
@Kartatz eu consegui fazer todo o procedimento, está funcionando lindo. 
Exceto por um novo probleminha, quando tento adicionar uma segunda conta da hotmart o SparkleC fecha inesperadamente, sabe pq? Quando ele começa a listar os cursos.

**Comment by Kartatz** [comment]
Sempre execute o SparkleC manualmente através do PowerShell. Se você abrir com o prompt de comando o Windows sempre fechará a janela quando o programa parar de escutar, fazendo com que você não veja nenhuma mensagem de erro.

E evite comentar sobre problemas distintos em uma mesma issue. Se possui uma nova dúvida ou problema, crie uma nova para isso.
