### ISSUE TITLE
Como instalar no linux?

### ISSUE THREAD

**Issue by runawaydevil** [Kartatz/SparkleC#25]
Eu já dei o git clone e copiei o repositório... E agora pessoa?
ahhhh

![image](https://user-images.githubusercontent.com/8763225/212439760-4a46c4a6-4b1b-4cd6-9968-b4d5b9a492c2.png)

**Comment by runawaydevil** [comment]
Desisto hahaha

**Comment by Kartatz** [comment]
Existem instruções claras sobre isso no README.
