### ISSUE TITLE
Ocorreu uma falha inesperada ao tentar localizar o cliente HTTP!

### ISSUE THREAD

**Issue by diegofilis** [Kartatz/SparkleC#27]
Clicando sobre o executável, ao escolher uma opção, o executável fecha.
Usando o CMD e depois escolhendo uma opção, aparece a mensagem com o erro: 
"Ocorreu uma falha inesperada ao tentar localizar o cliente HTTP!"
![cmd](https://user-images.githubusercontent.com/125092073/218198836-03d2cd01-e1d8-4192-9336-9ed31221f8f0.JPG)
O ffmpeg está instalado  certinho no Windows.

**Comment by diegofilis** [comment]
Baixei a versão anterior da ferramenta e deu certo. Obrigado.

**Comment by Kartatz** [comment]
Há alguma chance de você ter excluído o diretório `etc`, o qual vem incluído no arquivo compactado?

**Comment by Kartatz** [comment]
Vi na captura de tela que você renomeou o diretório onde o binário está localizado. Isso não deve ser feito, pois quebra a função que localiza o arquivo contendo os certificados SSL que são usados pela biblioteca HTTP.

Mantenha as pastas `bin` e `etc` intocadas. Nenhuma delas é descartável.
