### ISSUE TITLE
Falha para criar uma pasta com muitos caracteres 

### ISSUE THREAD

**Issue by Coogan085** [Kartatz/SparkleC#3]
Teria a possessividade de limitar os caracteres na hora de baixar, pois está dando erro , nas aulas que tem muitos caracteres 
https://imgur.com/EA5g9gE

**Comment by Kartatz** [comment]
Sim, eu já estou ciente deste problema. Uma possível solução para ele foi implementada há 3 dias no commit [[360d8c9](](https://github.com/Kartatz/SparkleC/commit/360d8c9820256e73a6cf339a29f4ae0979c9e015)https://github.com/Kartatz/SparkleC/commit/360d8c9820256e73a6cf339a29f4ae0979c9e015[)](https://github.com/Kartatz/SparkleC/commit/360d8c9820256e73a6cf339a29f4ae0979c9e015).

![IMG_20221121_012229_862.jpg](https://user-images.githubusercontent.com/105828205/203399264-11188ec8-43d9-4bfb-989a-51bf4e9676f0.jpg)

Basicamente eu implementei uma opção que possibilita ao usuário escolher se ele deseja usar os nomes dos módulos e aulas para nomear o conteúdo baixado ou um nome curto de até 10 caracteres gerado de forma aleatória.

Você pode baixar a última snapshot do programa e testar opção que mencionei?

[a.zip](https://github.com/Kartatz/SparkleC/files/10070518/a.zip)

**Comment by Coogan085** [comment]
compreendo, utilizo esse msm, mas será q não consegue um que não gere nome aleatório, continue com os nomes originais, mas de forma reduzida, só falta isso msm

**Comment by Kartatz** [comment]
Por razões técnicas isso não é viável.

Se está preocupado com a organização dos arquivos, o programa gera um HTML e um JSON no final do processo contendo uma árvore de informações sobre o que foi baixado, os quais você pode usar para navegar pelo conteúdo.

**Comment by Coogan085** [comment]
![image](https://user-images.githubusercontent.com/118844585/203558473-3e209b5d-271f-4d52-8ef8-abde6e2c0206.png)
Agora da esse erro e para o dowload

**Comment by FLzrnx** [comment]
Olá, estou com o mesmo problema.. não haveria a possibilidade de criar uma opção de ignorar o erro e continuar os proximos downloads?

**Comment by Coogan085** [comment]
![image](https://user-images.githubusercontent.com/118844585/205334145-441fee7a-5ae7-43ed-8c2e-e071b634098f.png)

**Comment by Kartatz** [comment]
Ambos os problemas mencionado na issue já foram resolvidos nos commits mais recentes.

@Coogan085 e @FLzrnx, se vocês possuem algum outro problema, criem uma nova issue e reporte-o lá.

Evitem puluir as issues já existentes com comentários que não possuem relação direta com o que já foi reportado. Isso nos ajudará a manter a organização e nos permite dar prioridade a problemas realmente relevantes.
