### ISSUE TITLE
Releases: Fix GLIBC flag version or use static

### ISSUE THREAD

**Issue by Sigmw** [Kartatz/SparkleC#30]
A linkagem da GLIBC nos releases segue da GLIBC 2.34/2.33 para as bibliotecas, fazendo com que o release não funcione em alguns sistemas com a versão da glibc diferente., você tem duas opções que eu acredito interessantes pra manter a portabilidade:

- Faça um port pra musl libc, em estático.
- Linke todo o binário em estático na glibc.

A vantagem da primeira opção é o tamanho menor que você vai ter linkando, um binário linkado estaticamente na glibc seria "desagrádavel".

Se estivesse com tempo, faria uma PR. Por sinal, parabéns pelo projeto!

**Comment by Kartatz** [comment]
Eu prefiro evitar fazer linkagem estática de binários sempre que possível. Isso torna implícito quais bibliotecas o programa original está usando e também faz com que o executável fique desnecessariamente maior.

Deixar todas as dependências explícitas e manter o código de terceiros em seus devidos binários é um conceito que gosto de seguir.

Sobre essa questão de versionamento do glibc, a única solução eficaz me parece ser a de compilar uma versão legacy dele e forçar o compilador a linkar os binários do SparkleC com ele, mas isso é algo que nunca testei.

**Comment by Sigmw** [comment]
No caso, falando de *PORTABILIDADE* entre sistemas operacionais Linux, eu acredito que ao menos a libc deveria ser linkada estaticamente.

**Comment by Kartatz** [comment]
Estou atualmente compilando os binários Linux (`x86`, `x86_64`, `armel` e `armhf`) usando uma versão alternativa do GCC, a qual usa o sysroot da versão legacy de um sistema (Debian) durante a linkagem.

Essa versão do sistema usa o [glibc 2.13](https://sourceware.org/glibc/wiki/Release/2.13) como base. Ela foi lançada no início de 2011, então tecnicamente qualquer distribuição Linux lançada nos últimos 12 anos deve ser capaz de executar o SparkleC sem problemas.
