### ISSUE TITLE
Dependências para compilação

### ISSUE THREAD

**Issue by ghost** [Kartatz/SparkleC#32]
Você poderia especificar no README.md as bibliotecas necessárias pra compilação do pacote ser bem sucedida? Eu só consegui porque tive que fuchicar e descobrir que o software utiliza uma versão do BearSSL.

**Comment by Sigmw** [comment]
Acabei de ver que você pode habilitar ou desabilitar as flags do SSL específico pela lista CMAKE, você pode criar um ./configure pra automatizar isso, o que acha?

**Comment by Kartatz** [comment]
55
CURLE_SEND_ERROR


No README eu menciono:

> O SparkleC inclui todas as suas dependências como submódulos no git.

E caso você navegue através do diretório [submodules](https://github.com/Kartatz/SparkleC/tree/master/submodules) presente na raiz do código fonte, vai notar que de fato elas estão listadas lá.

> você pode criar um ./configure pra automatizar isso

Eu uso o CMake porquê ele é suficientemente portátil ao ponto de poder ser usado sem muitas dificuldades até mesmo no Windows, o qual não dispõe de um shell posix-like nativo (que é algo requerido por programas como o `autoconf`). Não vejo razões para mudar isso.
