### ISSUE TITLE
SparkleC não baixa aulas do Panda Vídeo

### ISSUE THREAD

**Issue by Coogan085** [Kartatz/SparkleC#33]
![image](https://user-images.githubusercontent.com/118844585/221429541-bf990a7c-ff47-4ae8-9ee6-ce5c7a48f5f4.png)

Baixa tudo, menos os videos, pois não ta reconhecendo, como se tivesse arquivo texto

**Comment by Kartatz** [comment]
Entre em contato comigo atráves do Telegram em [@analogista](http://t.me/analogista) e forneça mais detalhes por lá.

**Comment by Coogan085** [comment]
Entrei em contato, aguardando seu retorno, @dillissilva

Em dom., 26 de fev. de 2023 16:39, Kartatz ***@***.***>
escreveu:

**Comment by Coogan085** [comment]
Deu um erro na hora de mover as pastas, te mandei no telegram

Em dom., 26 de fev. de 2023 23:37, Kartatz ***@***.***>
escreveu:
