### ISSUE TITLE
Erro ao dar continuidade ao download 

### ISSUE THREAD

**Issue by camilaamorims** [Kartatz/SparkleC#37]
Olá, muito obrigada pelo seu trabalho! 

Eu estou tendo alguns erros que tentarei reportar aqui.

Ao escolher o curso, chega um ponto que o cmd fecha subtamente. 

Ao gravar a tela consegui ver um erro ao tentar dar continuidade a um download. 

![Sem título](https://user-images.githubusercontent.com/127625982/224516953-a852bbbc-f752-4d44-a7bd-80e35003ad0f.png)

**Comment by Kartatz** [comment]
Apague o arquivo que está sendo mostrado na mensagem de erro.

Você provavelmente fechou o programa enquanto ele ainda estava baixando algo. Devido a isso, partes do que ele estava baixando antes ficaram salvas no seu disco e isso está impossibilitando que você baixe novos arquivos.

**Comment by camilaamorims** [comment]
Eu coloquei nome nos arquivos, como descubro a qual esse arquivo se refere ? 

Apaguei a última pasta que foi baixada ( por fazer sentido na minha cabeça estar dando erro no que foi baixado mais recentemente ), mas novamente quando fui fazer o download deu o mesmo erro no mesmo arquivo. 
Aconselha eu excluir a pasta toda do curso e começar dnv ? 

Obrigada!

**Comment by Kartatz** [comment]
Não estou me referindo ao que já foi baixado.

O arquivo que você precisa excluir está na imagem que você anexou. Na mensagem em vermelho.

**Comment by camilaamorims** [comment]
em quais casos você recomenda abrir pelo power shell ? e como eu faço para abrir por la ? =)

**Comment by camilaamorims** [comment]
Renomiei a pasta do curso que dava dando erro para ele não reconhecer mais, como previsto, ele iniciou um novo download. Ao baixar ocorreu tudo bem, até que chegou novamente na mesmo módulo que deu problema anteriormente, mas agora não apareceu nenhuma mensagem de erro, somente fechou o cmd. 

Segue o vídeo, ao final da gravação é quando fecha. 

https://user-images.githubusercontent.com/127625982/224522139-68fbf440-5c50-473f-8638-a5facf4aa14f.mp4

**Comment by Kartatz** [comment]
[rel.zip](https://github.com/Kartatz/SparkleC/files/10953531/rel.zip)

Faça um teste e confirme se o problema foi resolvido.

**Comment by camilaamorims** [comment]
Está baixando sem fechar, mas meu pc ta dando tela azul com o seguinte código " eexpected store exception " 


 obs: meu win defender está desativado.

**Comment by Kartatz** [comment]
Entre em contato comigo através do Telegram em [@analogista](http://t.me/analogista) para que eu possa fornecer um melhor suporte.
