### ISSUE TITLE
Erro ao executar | Windows 10 x64

### ISSUE THREAD

**Issue by alkabane** [Kartatz/SparkleC#38]
Erro: "Ocorreu uma falha inesperada ao tentar inicializar o cliente HTTP"

E só tive sucesso ao executar pelo cmd/powershell ao abrir pelo sparklec.exe ocorre erro :(

Agradeço desde já!

**Comment by Kartatz** [comment]
Leia o comentário que deixei para outra pessoa que reportou o mesmo problema que você [aqui](https://github.com/Kartatz/SparkleC/issues/27#issuecomment-1426454249).

**Comment by alkabane** [comment]
@Kartatz 
O erro era no antivirus enviando pra quarentena algumas Dlls
Muito Obrigado por tudo!
