### ISSUE TITLE
Arquivos .ts com Zero bytes

### ISSUE THREAD

**Issue by ramonsenadev** [Kartatz/SparkleC#4]
Olá, @Kartatz 
Primeiramente parabéns pelo projeto. Está funcionando muito bem! 🎉
Consegui rodar ele no Mac, então já é um feedback sobre o funcionamento nesse SO.

Ontem tive problemas relacionados a ssl com a versão do `master` quando compilei localmente, mas vi que você já até corrigiu aqui https://github.com/Kartatz/SparkleC/commit/3e02f367f3f75292a431549b224bc240fa430008
Obrigado!! 

Agora estou tendo um problema com o download de alguns arquivos específicos. Chega uma determinada aula que vários arquivos .ts são gerados com Zero bytes e o progresso do download no terminal fica travado em 0% / 100%.

Já apaguei os arquivos e diretório, tentei outras vezes, mas o erro persiste.

Como posso te ajudar a debugar e resolver o problema?

**Comment by Kartatz** [comment]
Pelo que você relatou, me parece estarem havendo falhas consecutivas durante o processo de download dos arquivos. Se o problema não é sua conexão de internet, então assumo que há algo de errado com os servidores da Hotmart.

Você ainda consegue reproduzir esse problema?

**Comment by ramonsenadev** [comment]
Sim. Continua acontecendo o mesmo... 😕

<img width="484" alt="image" src="https://user-images.githubusercontent.com/10205647/204152957-4d5c160e-a2ed-43ee-98a0-7e04bc2f66df.png">

<img width="183" alt="image" src="https://user-images.githubusercontent.com/10205647/204152831-57eb4bc8-9466-45fb-a9b9-449b51ef884b.png">

**Comment by Kartatz** [comment]
Você consegue reproduzir essa mesma aula sem problemas na própria Hotmart?

**Comment by ramonsenadev** [comment]
Consigo sim, @Kartatz
É uma aula bem longa inclusive... Eu dei uma pausa nisso agora, mas durante o fim de semana tento novamente e caso eu consiga debugar, trago aqui.

**Comment by Kartatz** [comment]
Nenhuma outra pessoa reportou um problema semelhante ao seu. Também fui incapaz de reproduzi-lo por conta própria.

Tendo isso mente, estarei fechando essa issue por falta de atividade. Caso tenha mais alguma infornação a adicionar, sinta-se livre para reabri-la.
