### ISSUE TITLE
Problema na instalação no macOS

### ISSUE THREAD

**Issue by egmj914** [Kartatz/SparkleC#41]
Olá, tentei fazer a instalação pelo terminal mas recebi o seguinte erro, estou usando o BigSur com o Python 3.11.2, tentei todas as versões
![Captura de Tela 2023-03-22 às 20 35 50](https://user-images.githubusercontent.com/128651828/227063081-61fbe6c1-7051-4827-bc99-143a66952af4.png)

**Comment by Kartatz** [comment]
Estou ciente do problema. Ele foi resolvido recentemente.

A solução estará disponível na próxima atualização.

**Comment by Kartatz** [comment]
Foi resolvido na versão 0.5.
