### ISSUE TITLE
Sample rate not set

### ISSUE THREAD

**Issue by guruhimalaiaz** [Kartatz/SparkleC#43]
Estou usando o W10, e quando tento baixar um curso da Hotmart encontro esse problema sempre, seja pelo executável ou pelo powershell
![sample](https://user-images.githubusercontent.com/129202120/228309989-8e3efd55-b799-43b2-933e-9ae4e545a473.PNG)

**Comment by Kartatz** [comment]
Entre em contato comigo através do Telegram em [@analogista](http://t.me/analogista) para que eu possa ajudar.

**Comment by Kartatz** [comment]
Estou fechando essa issue por falta de atividade. Caso tenha mais alguma infornação a adicionar, sinta-se livre para reabri-la.
