### ISSUE TITLE
Erro no download de video na HotM@rt

### ISSUE THREAD

**Issue by drleonunes** [Kartatz/SparkleC#49]
Olá, boa tarde.
Notei uma falha durante o uso do app em um de meus cursos na HotM@art. Ele interrompe e sai para o prompt. 
O erro está no anexo, onde adicionei um print de minha tela. 
![Screenshot_2023-04-17-15-51-22-144_com termux](https://user-images.githubusercontent.com/951748/232583570-2e228e0c-7759-4666-9656-dd51057eea79.jpg)

Obrigado.

**Comment by layofrederico** [comment]
O mesmo erro ocorre comigo

**Comment by wesleyclzns** [comment]
Comigo não dá nenhum erro. A tela do prompt fecha e não tem nenhum arquivo na pasta

**Comment by wesleyclzns** [comment]
Comigo esta acontecendo um erro tambem na hora de baixar 
```
ffmpeg' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
- Ocorreu uma falha inesperada ao tentar processar a mídia!
```
![image](https://github.com/Kartatz/SparkleC/assets/20156708/4409f697-90b8-423a-8cf0-7c87748e6a62)

**Comment by Kartatz** [comment]
> Comigo esta acontecendo um erro tambem na hora de baixar 
> ```
> ffmpeg' não é reconhecido como um comando interno
> ou externo, um programa operável ou um arquivo em lotes.
> - Ocorreu uma falha inesperada ao tentar processar a mídia!
> ```
> ![image](https://github.com/Kartatz/SparkleC/assets/20156708/4409f697-90b8-423a-8cf0-7c87748e6a62)
> 

Você está usando uma versão antiga. Vá até a seção de lançamentos no GitHub e baixe a versão mais recente.

**Comment by Kartatz** [comment]
Estou fechando essa issue por falta de atividade. Caso tenha mais alguma infornação a adicionar, sinta-se livre para reabri-la.
