### ISSUE TITLE
Não consegue baixar da plataforma Kiwify

### ISSUE THREAD

**Issue by cmteles** [Kartatz/SparkleC#50]
Não consigo baixar o conteúdo da plataforma Kiwify. O aplicativo sempre fecha e não inicia o download mesmo acessando direto pelo CMD.

![image](https://user-images.githubusercontent.com/47121334/232868132-d2ada709-dbce-42c7-b09a-73e938557014.png)

**Comment by Kartatz** [comment]
Não consegui reproduzir.
