### ISSUE TITLE
Arquivos ficam inacessiveis

### ISSUE THREAD

**Issue by PerseuFW** [Kartatz/SparkleC#51]
Ao utilizar a nomenclatura original , se for muito extenso o curso, o sparkle inutiliza a pasta, escondendo os arquivos, mas ao compactar , la estão consumindo espaço.
![image](https://user-images.githubusercontent.com/132235393/235549728-2dd7aa2b-2a94-4501-8b41-d800c4fbd7a0.png)

**Comment by Kartatz** [comment]
Essa é uma limitação do Windows, não do SparkleC.

Você pode contornar isso usando o programa em um sistema Linux ou baixando os arquivos sem manter os nomes originais.

**Comment by PerseuFW** [comment]
Entendi, obg pelo FB. Irei tentar emular algum linux aqui na maquina msm.
