### ISSUE TITLE
Não consigo compilar no windows11

### ISSUE THREAD

**Issue by rafael237** [Kartatz/SparkleC#54]
Primeiramente, gostaria de parabenizar pelo projeto, app muito rápido e funcional.

Tento fazer a compilação pelo windows 11, mas ao executar o comando: cmake -DCMAKE_BUILD_TYPE=MinSizeRel .

ele retorna esse erro:
------------------------------------------------------------------------------------
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:3 (project):
  Running

   'nmake' '-?'

  failed with:

   O sistema não pode encontrar o arquivo especificado

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
------------------------------------------------------------------------------------
Dai modifiquei o arquivo: CMakeLists.txt
 
adcionando essas linhas: 
set(CMAKE_C_COMPILER "C:/MinGW/bin/gcc.exe")
set(CMAKE_CXX_COMPILER "C:/MinGW/bin/cpp.exe")

e tentei esse comando: cmake -S . -B Build -G "MinGW Makefiles" 

continua dando erro a compilação. Acredito que seja por questão do compilador. Vi que falou sobre o gcc, porém ficou confuso a tradução em entender se é para usa-lo ou não.

Em fim, poderia me indicar o compilador que usa ou algum que seja compativel ? Ou qual seria o meu erro? Sou iniciante, mas tenho muita disposição em aprender e ajudá-lo no respectivo projeto. 
Obrigado.

**Comment by rafael237** [comment]
também tente esse comando: cmake -S . -B Build -G "MinGW Makefiles"

CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- The C compiler identification is GNU 6.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- curl version=[8.0.1-DEV]
-- Could NOT find Perl (missing: PERL_EXECUTABLE)
-- Looking for getch in ws2_32;
-- Looking for getch in ws2_32; - found
-- Looking for getch in winmm;ws2_32
-- Looking for getch in winmm;ws2_32 - found
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (BEARSSL)
  does not match the name of the calling package (BearSSL).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  submodules/curl/CMake/FindBearSSL.cmake:29 (find_package_handle_standard_args)
  submodules/curl/CMakeLists.txt:519 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found BEARSSL: submodules/bearssl/inc
-- Looking for include file windows.h
-- Looking for include file windows.h - found
-- Looking for include files windows.h, ws2tcpip.h
-- Looking for include files windows.h, ws2tcpip.h - found
-- Looking for 3 include files windows.h, ..., winsock2.h
-- Looking for 3 include files windows.h, ..., winsock2.h - found
-- Looking for 4 include files windows.h, ..., wincrypt.h
-- Looking for 4 include files windows.h, ..., wincrypt.h - found
-- Looking for 5 include files windows.h, ..., inttypes.h
-- Looking for 5 include files windows.h, ..., inttypes.h - found
-- Looking for 6 include files windows.h, ..., sys/filio.h
-- Looking for 6 include files windows.h, ..., sys/filio.h - not found
-- Looking for 6 include files windows.h, ..., sys/ioctl.h
-- Looking for 6 include files windows.h, ..., sys/ioctl.h - not found
-- Looking for 6 include files windows.h, ..., sys/resource.h
-- Looking for 6 include files windows.h, ..., sys/resource.h - not found
-- Looking for 8 include files windows.h, ..., sys/un.h
-- Looking for 8 include files windows.h, ..., sys/un.h - not found
-- Looking for 9 include files windows.h, ..., sys/xattr.h
-- Looking for 9 include files windows.h, ..., sys/xattr.h - not found
-- Looking for 9 include files windows.h, ..., arpa/tftp.h
-- Looking for 9 include files windows.h, ..., arpa/tftp.h - not found
-- Looking for 10 include files windows.h, ..., idn2.h
-- Looking for 10 include files windows.h, ..., idn2.h - not found
-- Looking for 10 include files windows.h, ..., ifaddrs.h
-- Looking for 10 include files windows.h, ..., ifaddrs.h - not found
-- Looking for 11 include files windows.h, ..., libgen.h
-- Looking for 11 include files windows.h, ..., libgen.h - found
-- Looking for 12 include files windows.h, ..., locale.h
-- Looking for 12 include files windows.h, ..., locale.h - found
-- Looking for 13 include files windows.h, ..., netinet/tcp.h
-- Looking for 13 include files windows.h, ..., netinet/tcp.h - not found
-- Looking for linux/tcp.h
-- Looking for linux/tcp.h - not found
-- Looking for 13 include files windows.h, ..., poll.h
-- Looking for 13 include files windows.h, ..., poll.h - not found
-- Looking for 15 include files windows.h, ..., ssl.h
-- Looking for 15 include files windows.h, ..., ssl.h - not found
-- Looking for 15 include files windows.h, ..., stdatomic.h
-- Looking for 15 include files windows.h, ..., stdatomic.h - found
-- Looking for 16 include files windows.h, ..., stdbool.h
-- Looking for 16 include files windows.h, ..., stdbool.h - found
-- Looking for 17 include files windows.h, ..., stdint.h
-- Looking for 17 include files windows.h, ..., stdint.h - found
-- Looking for 20 include files windows.h, ..., stropts.h
-- Looking for 20 include files windows.h, ..., stropts.h - not found
-- Looking for 21 include files windows.h, ..., unistd.h
-- Looking for 21 include files windows.h, ..., unistd.h - found
-- Looking for 22 include files windows.h, ..., stddef.h
-- Looking for 22 include files windows.h, ..., stddef.h - found
-- Looking for 23 include files windows.h, ..., sys/utsname.h
-- Looking for 23 include files windows.h, ..., sys/utsname.h - not found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of ssize_t
-- Check size of ssize_t - done
-- Check size of long long
-- Check size of long long - done
-- Check size of long
-- Check size of long - done
-- Check size of int
-- Check size of int - done
-- Check size of __int64
-- Check size of __int64 - done
-- Check size of time_t
-- Check size of time_t - done
-- Looking for fchmod
-- Looking for fchmod - not found
-- Looking for basename
-- Looking for basename - found
-- Looking for socketpair
-- Looking for socketpair - not found
-- Looking for recv
-- Looking for recv - found
-- Looking for send
-- Looking for send - found
-- Looking for sendmsg
-- Looking for sendmsg - not found
-- Looking for strtok_r
-- Looking for strtok_r - not found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for alarm
-- Looking for alarm - not found
-- Looking for getppid
-- Looking for getppid - not found
-- Looking for utimes
-- Looking for utimes - not found
-- Looking for getpwuid_r
-- Looking for getpwuid_r - not found
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for siginterrupt
-- Looking for siginterrupt - not found
-- Looking for getaddrinfo
-- Looking for getaddrinfo - not found
-- Looking for freeaddrinfo
-- Looking for freeaddrinfo - not found
-- Looking for pipe
-- Looking for pipe - not found
-- Looking for ftruncate
-- Looking for ftruncate - found
-- Looking for getpeername
-- Looking for getpeername - found
-- Looking for getsockname
-- Looking for getsockname - found
-- Looking for if_nametoindex
-- Looking for if_nametoindex - not found
-- Looking for getrlimit
-- Looking for getrlimit - not found
-- Looking for setlocale
-- Looking for setlocale - found
-- Looking for setmode
-- Looking for setmode - found
-- Looking for setrlimit
-- Looking for setrlimit - not found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for mach_absolute_time
-- Looking for mach_absolute_time - not found
-- Looking for inet_ntop
-- Looking for inet_ntop - not found
-- Looking for inet_pton
-- Looking for inet_pton - not found
-- Looking for fsetxattr
-- Looking for fsetxattr - not found
-- Check size of sa_family_t
-- Check size of sa_family_t - failed
-- Check size of ADDRESS_FAMILY
-- Check size of ADDRESS_FAMILY - failed
-- Performing Curl Test HAVE_FCNTL_O_NONBLOCK
-- Performing Curl Test HAVE_FCNTL_O_NONBLOCK - Failed
-- Performing Curl Test HAVE_IOCTLSOCKET
-- Performing Curl Test HAVE_IOCTLSOCKET - Success
-- Performing Curl Test HAVE_IOCTLSOCKET_CAMEL
-- Performing Curl Test HAVE_IOCTLSOCKET_CAMEL - Failed
-- Performing Curl Test HAVE_IOCTLSOCKET_CAMEL_FIONBIO
-- Performing Curl Test HAVE_IOCTLSOCKET_CAMEL_FIONBIO - Failed
-- Performing Curl Test HAVE_IOCTLSOCKET_FIONBIO
-- Performing Curl Test HAVE_IOCTLSOCKET_FIONBIO - Success
-- Performing Curl Test HAVE_IOCTL_FIONBIO
-- Performing Curl Test HAVE_IOCTL_FIONBIO - Failed
-- Performing Curl Test HAVE_IOCTL_SIOCGIFADDR
-- Performing Curl Test HAVE_IOCTL_SIOCGIFADDR - Failed
-- Performing Curl Test HAVE_SETSOCKOPT_SO_NONBLOCK
-- Performing Curl Test HAVE_SETSOCKOPT_SO_NONBLOCK - Failed
-- Performing Curl Test HAVE_BOOL_T
-- Performing Curl Test HAVE_BOOL_T - Success
-- Performing Curl Test HAVE_FILE_OFFSET_BITS
-- Performing Curl Test HAVE_FILE_OFFSET_BITS - Failed
-- Performing Curl Test HAVE_VARIADIC_MACROS_C99
-- Performing Curl Test HAVE_VARIADIC_MACROS_C99 - Success
-- Performing Curl Test HAVE_VARIADIC_MACROS_GCC
-- Performing Curl Test HAVE_VARIADIC_MACROS_GCC - Success
-- Performing Curl Test HAVE_ATOMIC
-- Performing Curl Test HAVE_ATOMIC - Success
-- Check size of off_t
-- Check size of off_t - done
-- Check size of curl_off_t
-- Check size of curl_off_t - done
-- Performing Curl Test HAVE_WIN32_WINNT
-- Performing Curl Test HAVE_WIN32_WINNT - Success
-- Found _WIN32_WINNT=0x0500
-- Performing Curl Test HAVE_GLIBC_STRERROR_R
-- Performing Curl Test HAVE_GLIBC_STRERROR_R - Failed
-- Performing Curl Test HAVE_POSIX_STRERROR_R
-- Performing Curl Test HAVE_POSIX_STRERROR_R - Success
-- Performing Curl Test HAVE_CLOCK_GETTIME_MONOTONIC
-- Performing Curl Test HAVE_CLOCK_GETTIME_MONOTONIC - Failed
-- Performing Curl Test HAVE_BUILTIN_AVAILABLE
-- Performing Curl Test HAVE_BUILTIN_AVAILABLE - Failed
-- Performing Test HAVE_MSG_NOSIGNAL
-- Performing Test HAVE_MSG_NOSIGNAL - Failed
-- Performing Test HAVE_STRUCT_TIMEVAL
-- Performing Test HAVE_STRUCT_TIMEVAL - Success
-- Check size of struct sockaddr_storage
-- Check size of struct sockaddr_storage - done
-- Performing Test HAVE_POLL_FINE
-- Performing Test HAVE_POLL_FINE - Failed
-- Looking for CryptAcquireContext
-- Looking for CryptAcquireContext - found
-- Performing Test HAVE_MINGW_ORIGINAL
-- Performing Test HAVE_MINGW_ORIGINAL - Success
-- Enabled features: SSL IPv6 Largefile HTTPS-proxy unicode threadsafe
-- Enabled protocols: HTTP HTTPS
-- Enabled SSL backends: BearSSL
-- Performing Test HAS_NO_FORMAT_TRUNCATION
-- Performing Test HAS_NO_FORMAT_TRUNCATION - Success
C compiler: GNU
-- Looking for include file endian.h
-- Looking for include file endian.h - not found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file sched.h
-- Looking for include file sched.h - not found
-- Looking for include file sys/param.h
-- Looking for include file sys/param.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for close
-- Looking for close - found
-- Looking for getpid
-- Looking for getpid - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for open
-- Looking for open - found
-- Looking for read
-- Looking for read - found
-- Looking for sched_yield
-- Looking for sched_yield - not found
-- Check size of __int64
-- Check size of __int64 - done
-- Check size of int64_t
-- Check size of int64_t - done
-- Check size of long long
-- Check size of long long - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of __int32
-- Check size of __int32 - done
-- Check size of long
-- Check size of long - done
-- Check size of int
-- Check size of int - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of __uint32
-- Check size of __uint32 - failed
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of __uint16
-- Check size of __uint16 - failed
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of __uint8
-- Check size of __uint8 - failed
-- Check size of ssize_t
-- Check size of ssize_t - done
-- Check size of SSIZE_T
-- Check size of SSIZE_T - failed
-- Looking for strtoq
-- Looking for strtoq - not found
-- Looking for _strtoi64
-- Looking for _strtoi64 - found
-- Looking for localeconv
-- Looking for localeconv - found
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Performing Test HAVE___INLINE
-- Performing Test HAVE___INLINE - Success
-- Performing Test HAVE___INLINE__
-- Performing Test HAVE___INLINE__ - Success
-- Performing Test HAVE_SYNC_BUILTINS
-- Performing Test HAVE_SYNC_BUILTINS - Success
-- Performing Test HAVE_ATOMIC_BUILTINS
-- Performing Test HAVE_ATOMIC_BUILTINS - Success
-- Performing Test DSYMVER_WORKS
-- Performing Test DSYMVER_WORKS - Success
CMake Warning (dev) at submodules/tidy/CMakeLists.txt:26 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The CXX compiler identification is unknown
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: C:/MinGW/bin/cpp.exe
-- Check for working CXX compiler: C:/MinGW/bin/cpp.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:60 (message):
  The C++ compiler

    "C:/MinGW/bin/cpp.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/Projeto DownloadVideo/Projeto software em  C/SparkleC/CMakeFiles/CMakeScratch/TryCompile-2g7fx4

    Run Build Command(s):C:/Program Files/CMake/bin/cmake.exe -E env VERBOSE=1 C:/MinGW/bin/mingw32-make.exe -f Makefile cmTC_0abf5/fast && C:/MinGW/bin/mingw32-make.exe  -f CMakeFiles\cmTC_0abf5.dir\build.make CMakeFiles/cmTC_0abf5.dir/build
    mingw32-make.exe[1]: Entering directory 'D:/Projeto DownloadVideo/Projeto software em  C/SparkleC/CMakeFiles/CMakeScratch/TryCompile-2g7fx4'
    Building CXX object CMakeFiles/cmTC_0abf5.dir/testCXXCompiler.cxx.obj
    C:\MinGW\bin\cpp.exe    -o CMakeFiles\cmTC_0abf5.dir\testCXXCompiler.cxx.obj -c "D:\Projeto DownloadVideo\Projeto software em  C\SparkleC\CMakeFiles\CMakeScratch\TryCompile-2g7fx4\testCXXCompiler.cxx"
    cpp.exe: fatal error: '-c' is not a valid option to the preprocessor
    compilation terminated.
    CMakeFiles\cmTC_0abf5.dir\build.make:76: recipe for target 'CMakeFiles/cmTC_0abf5.dir/testCXXCompiler.cxx.obj' failed
    mingw32-make.exe[1]: *** [CMakeFiles/cmTC_0abf5.dir/testCXXCompiler.cxx.obj] Error 1
    mingw32-make.exe[1]: Leaving directory 'D:/Projeto DownloadVideo/Projeto software em  C/SparkleC/CMakeFiles/CMakeScratch/TryCompile-2g7fx4'
    Makefile:126: recipe for target 'cmTC_0abf5/fast' failed
    mingw32-make.exe: *** [cmTC_0abf5/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  submodules/tidy/CMakeLists.txt:26 (project)


-- Configuring incomplete, errors occurred!

**Comment by Kartatz** [comment]
> `set(CMAKE_CXX_COMPILER "C:/MinGW/bin/cpp.exe")`

O cpp.exe não é um compilador, mas sim um
pré-processador do C. Você não conseguirá compilar nada usando ele.

O erro mencionado por você aponta justamente isso:

```
-- Check for working CXX compiler: C:/MinGW/bin/cpp.exe - broken
```

Acho que você deveria estar usando o `g++.exe` em vez desse.

**Comment by rafael237** [comment]
Obrigado por responder. Realmente usar o g++.exe resolveu o problema, porém agora aparece outro problema relacionado ao ffmpeg.

ao executar o comando:  cmake -DCMAKE_BUILD_TYPE=MinSizeRel -G "MinGW Makefiles"

-> TIDY_SO_VERSION = 59. This is an ODD (development) release.
-- *** Debug Logging is NOT enabled.
-- *** Also building DLL library SHARED, version 5.9.20, date 2022.01.25
-- Configuring FFmpeg
CMake Error at CMakeLists.txt:501 (execute_process):
  execute_process error getting child return code: O sistema não pode
  encontrar o arquivo especificado


-- Configuring incomplete, errors occurred!

**Comment by rafael237** [comment]
o erro se encontra nesta parte:

if (NOT EXISTS "${FFMPEG_BUILD_DIRECTORY}/Makefile")
	message("-- Configuring FFmpeg")
	
	execute_process(
		COMMAND bash
		"${FFMPEG_SOURCE_DIRECTORY}/configure"
		${FFMPEG_CONFIGURE_FLAGS}
		WORKING_DIRECTORY "${FFMPEG_BUILD_DIRECTORY}"
		COMMAND_ERROR_IS_FATAL ANY
	)

eu preciso ter o bash instalado? pelo cmd do windows funciona?

**Comment by Kartatz** [comment]
Tente alterar o comando abaixo:

```cmake
execute_process(
	COMMAND bash
	"${FFMPEG_SOURCE_DIRECTORY}/configure"
	${FFMPEG_CONFIGURE_FLAGS}
	WORKING_DIRECTORY "${FFMPEG_BUILD_DIRECTORY}"
)
``` 

Para que fique desse modo:

```cmake
execute_process(
	COMMAND "${FFMPEG_SOURCE_DIRECTORY}/configure"
	${FFMPEG_CONFIGURE_FLAGS}
	WORKING_DIRECTORY "${FFMPEG_BUILD_DIRECTORY}"
)
```

Mas em todo caso, o ffmpeg compila os binários de um modo diferente das demais dependências que uso. Esse procedimento nunca foi testado no Windows e até então eu considerava que não era suportado.

**Comment by rafael237** [comment]
Funcinou, agora ele para nessa parte:

após o comando: cmake --build .
...
[ 53%] Linking C shared library libbearssl.dll
[ 53%] Built target bearssl
[ 53%] -- Building FFmpeg
'make' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
CMakeFiles\ffmpeg.dir\build.make:71: recipe for target 'ffmpeg-build/binaries' failed
mingw32-make.exe[2]: *** [ffmpeg-build/binaries] Error 1
CMakeFiles\Makefile2:220: recipe for target 'CMakeFiles/ffmpeg.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/ffmpeg.dir/all] Error 2
Makefile:154: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

**Comment by rafael237** [comment]
Na verdade, fazer isso:
execute_process(
	COMMAND "${FFMPEG_SOURCE_DIRECTORY}/configure"
	${FFMPEG_CONFIGURE_FLAGS}
	WORKING_DIRECTORY "${FFMPEG_BUILD_DIRECTORY}"
)

não resolveu, deveria ter sido criado arquivos na pasta: ffmpeg-build. Mas, obrigado pela tentativa.

**Comment by rafael237** [comment]
Esse processo de compilação é para Linux, quero para windows, para gerar o .exe
Consegue me orientar quanto a isso?Qualquer ajuda é bem vinda. Obrigado mais uma vez e agradeço de verdade pela atenção.

**Comment by Kartatz** [comment]
Compilar o ffmpeg requer um ambiente unix-like. Você precisa instalar ferramentas como o `bash` e o `make`.

Mas como falei antes, nunca tentei compilar o SparkleC no Windows. Em teoria funciona, mas não posso afirmar com certeza.

Você pode tentar, mas não garanto que irá funcionar. Você está basicamente "sozinho" nessa.

**Comment by Kartatz** [comment]
Se você precisa de uma compilação do último commit apenas para fins de uso, poderá obtê-la através do GitHub Actions desse repositório.

Na página inicial do repositório, clique em **Actions**, selecione o commit mais recente e baixe o arquivo **artifact**. Nele estão binários para todos os sistemas suportados pelo SparkleC.

**Comment by rafael237** [comment]
Pelo Linux Kali eu consegui compilar, porém eu quero gerar um executavel para windows. Pelas minhas pesquisas posso usar a Cross-compilation , ou seja, pelo linux onsigo compilar um .exe para windows. Sabe informar algo sobre?

**Comment by rafael237** [comment]
Eu quero para fins de estudo, criar novas funções. Ganhar mais experiência e contribuir.

**Comment by Kartatz** [comment]
Sim, você pode usar o [llvm-mingw](https://github.com/mstorsjo/llvm-mingw) para realizar uma compilação cruzada no Linux para produzir binários para Windows:

Eis abaixo os comandos que você pode usar para isso:

```bash
# Instalar e configurar o llvm-mingw
declare -r LLVM_MINGW_TAG='20230320'
declare -r LLVM_MINGW_TARBALL='/tmp/llvm-mingw.tar.xz'
declare -r LLVM_MINGW_URL="https://github.com/mstorsjo/llvm-mingw/releases/download/${LLVM_MINGW_TAG}/llvm-mingw-${LLVM_MINGW_TAG}-msvcrt-ubuntu-18.04-x86_64.tar.xz"

curl --retry 10 --retry-delay 3 --silent --location --url "${LLVM_MINGW_URL}" --output "${LLVM_MINGW_TARBALL}"
tar --directory="$(dirname "${LLVM_MINGW_TARBALL}")" --extract --file="${LLVM_MINGW_TARBALL}"

export LLVM_MINGW_HOME="$(dirname "${LLVM_MINGW_TARBALL}")/$(basename "${LLVM_MINGW_URL}" '.tar.xz')"
export PATH="${PATH}:$(dirname "${LLVM_MINGW_TARBALL}")/$(basename "${LLVM_MINGW_URL}" '.tar.xz')/bin"

# Configurar e compilar o SparkleC
cmake -DCMAKE_TOOLCHAIN_FILE='./.github/workflows/cmake_toolchains/x86_64-w64-mingw32.cmake' \
    -DCMAKE_INSTALL_PREFIX='x86_64-w64-mingw32' \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    ./
cmake --build ./
```

**Comment by rafael237** [comment]
Funcionou perfeitamente, obrigado.
