### ISSUE TITLE
The requested URL returned error: 401

### ISSUE THREAD

**Issue by rodrigolgl** [Kartatz/SparkleC#55]
Parabéns pelo projeto. Realmente incrível.
Eu usava o SparkleC até em abril. Tentei logar no estratégia concursos hoje e quando tento logar no usuário válido o sistema diz que o login expirou e pede para fazer novo login.

Quando tento fazer novo login, é apresentada a seguinte mensagem:

"Ocorreu uma falha inesperada ao tentar conectar com o servidor HTTP: The requested URL returned error: 401"

Executei o programa pelo CMD. Desativei o Windows Defender também. O usuário e senha estão corretos. A senha não possue caracteres especiais.

Tentei executar pelo PowerShell e dá a mesma mensagem.

Saberia o que pode estar acontecendo?

Obrigado

**Comment by Kartatz** [comment]
Não consegui reproduzir seu problema.

Confirme se as credenciais digitadas estão corretas (exemplo: teste se você consegue acessar normalmente pelo site) e confira se você está usando a [versão mais recente do programa](https://github.com/Kartatz/SparkleC/releases/latest/download/x86_64-w64-mingw32.zip).
