### ISSUE TITLE
IA Expert Academy

### ISSUE THREAD

**Issue by cassioarapiun** [Kartatz/SparkleC#56]
![Captura de tela 2023-06-17 011815](https://github.com/Kartatz/SparkleC/assets/97003257/7774779b-2d51-4486-8263-0fbb89c03e96)
Olá, tudo bem? Bom, comigo está acontecendo o seguinte problema:

Testei a versão Release e a Anterior , na **Hotmart** está uma maravilha porém, na **IA Expert Academy** executa tudo certinho os procedimentos mas, quando começa a fazer o **download** 3 segundo fecha, ai não vai de forma alguma.

**Comment by Kartatz** [comment]
O problema ocorre em um curso específico ou pode ser encontrado ao baixar qualquer outro?

**Comment by cassioarapiun** [comment]
> O problema ocorre em um curso específico ou com todos?

Bom teste em 2 apenas , vou testar em outro aqui

**Comment by Kartatz** [comment]
Entre em contato comigo via e-email através do endereço em luissilvaferreira@protonmail.com para que possamos discutir isso com mais detalhes.

**Comment by cassioarapiun** [comment]
Mandei lá, msg

**Comment by Kartatz** [comment]
Você pode testar e confirmar se o problema foi de fato resolvido?

![x86_64-w64-mingw32.zip](https://github.com/Kartatz/SparkleC/files/11780114/x86_64-w64-mingw32.zip)
