### ISSUE TITLE
Programa fecha após escolher hotmart

### ISSUE THREAD

**Issue by narifi** [Kartatz/SparkleC#57]
Olá!
fui testar a versão mais recente do programa (a última que eu estava usando era SparkleC v0.2) e, ao digitar "1" e confirmar, ele fecha na mesma hora. Já tentei desativar o anti vírus e não fez efeito.

Poderia me ajudar?

muito obrigada

**Comment by narifi** [comment]
Esqueci de mencionar, estou usando o windows 10 de 64 bits

**Comment by Kartatz** [comment]
Seu problema parece estar relacionado ao que foi reportado na #38 e #27. Leia elas e veja se alguma das soluções discutidas resolvem seu problema.

E um adendo: você deve sempre executar o SparkleC através de um terminal interativo, do contrario não conseguirá ver a mensagem de erro caso algum problema ocorra, visto que ele fechará de imediato.

**Comment by narifi** [comment]
Acabei de executar pelo terminal e apareceu o seguinte:

- O arquivo de configurações localizado em 'C:\Users\Taís\AppData\Roaming\SparkleC\Hotmart\accounts.json' possui um formato inválido!

apaguei o arquivo e tentei de novo (acredito que ele foi gerado pela antiga versão?), aí funcionou

coloquei pra baixar um curso e por ora está funcionando

muito obrigada pela resposta rápida :)

**Comment by narifi** [comment]
ah, uma sugestão. talvez seja interessante citar essa importância do terminal no read me? como o texto orienta apenas abrir diretamente o executável, nem havia passado pela minha cabeça a possibilidade de usar o cmd nele rs

**Comment by douglassilverira** [comment]
Estou com esse problema, de uma hora pra outra quando entra na minha conta logo em seguida fecha tudo
