### ISSUE TITLE
Programa fechando sozinho durante download no Hotmart

### ISSUE THREAD

**Issue by zuzirtex** [Kartatz/SparkleC#58]
Colegas,

Estou baixando um curso no Hotmart e, em determinado ponto, o terminal se encerra sozinho. Eu consegui capturar a seguinte mensagem, antes de o programar fechar. Podem me ajudar? 

Estou usando a última versão do SparkleC e Windows 11.

```
+ Baixando seguimentos de mídia de 'https://vod-akm.play.hotmart.com/video/xxxxx/hls/1080/playlist-1080-t-xxxxxx.m3u8?hdntl=exp=1690061208~acl=/*~data=hdntl~hmac=c3792dc52a60e356b1997e0fd317869317f26d8169b63c55a4feb8198dfa06ee&app=f57b1bb2-30e3-4fd0-9c59-cfe00909f280' para 'C:\Users\xxxx\AppData\Local\Temp\SparkleC'
+ Exportando lista de reprodução M3U8 para 'C:\Users\xxx\AppData\Local\Temp\SparkleCxxxxxxxxxxxx.ts.m3u8'
+ Concatenando seguimentos de mídia baixados para um único arquivo em 'C:\Users\heuds\AppData\Local\Temp\SparkleC\xxxxxxxxxxx.ts'
[mpegts @ 000002817ee90000] sample rate not set
- Ocorreu uma falha inesperada ao tentar concatenar os seguimentos de mídia de 'C:\Users\xxx\AppData\Local\Temp\SparkleC\xxxxxxxxxxxx.ts.m3u8' para um único arquivo em 'C:\Users\xxx\AppData\Local\Temp\SparkleC\xxxxxxxxxx.ts': Invalid argument
```

**Comment by Kartatz** [comment]
Entre em contato comigo via e-mail no luissilvaferreira@protonmail.com para que possamos discutir melhor o problema.

**Comment by Kartatz** [comment]
[x86_64-w64-mingw32.zip](https://github.com/Kartatz/SparkleC/files/12138406/x86_64-w64-mingw32.zip).

Você pode confirmar se o problema foi resolvido?

**Comment by zuzirtex** [comment]
O problema foi resolvido. O programa não está apresentando erro no ponto específico. Os arquivos estão sendo baixados, caso aconteça novamente, retornarei aqui. Obrigado pelo auxílio e atenção!
