### ISSUE TITLE
Erro ao tentar Criar Diretorio 

### ISSUE THREAD

**Issue by BrunoMota0** [Kartatz/SparkleC#6]
![image](https://user-images.githubusercontent.com/119694085/205349970-074a2535-106d-4fd3-b07c-d1a6d0712686.png)

Está dando erro ao tentar criar um diretório

**Comment by Kartatz** [comment]
Você está usando uma versão antiga do programa.

Teste com uma snapshot recente antes de reportar qualquer problema.

**Comment by BrunoMota0** [comment]
Pode me ensinar a baixar a versão atualizada ?

**Comment by Kartatz** [comment]
[x86_64-w64-mingw32.zip](https://github.com/Kartatz/SparkleC/files/10145114/x86_64-w64-mingw32.zip)

Aqui está a versão contendo as alterações mais recentes. Teste com ela.

**Comment by CassioPaz66** [comment]
Boa noite

O script sparkle está apresentando falha 
Na versão anterior a mensagem é a que segue:
"- Sua sessão expirou ou foi revogada, refaça o login!"

Com a versão atualizada [x86_64-w64-mingw32.zip]
A mensagem alterou para :
"- Não foi possível realizar a autenticação: A requisição para um servidor HTTP não pôde ser completada com êxito"

Refiz login e inclusive mudei senha, mas não encontro a falha.

Tenho curso em andamento que gostaria de fazer copia e se possivel até mesmo compartilhar.

**Comment by BrunoMota0** [comment]
Poderia mandar a versão atualizada?

Em ter, 6 de dez de 2022 00:53, Kartatz ***@***.***> escreveu:
