### ISSUE TITLE
Kiwify com problemas

### ISSUE THREAD

**Issue by fridafridex** [Kartatz/SparkleC#60]
Os cursos da Kiwify estão sem áudio e a imagem está travada, além de não baixar o curso inteiro, no processo apareceu esses erros: h264 @ 000001cc9e372de0] error while decoding MB 111 68, bytestream -10

**Comment by fridafridex** [comment]
meu sistema é  win x64 estou usando a versão 7

**Comment by fridafridex** [comment]
já instalei o ffmpeg corretamente e fiz pelo terminal

**Comment by fridafridex** [comment]
o que pode estar acontecendo pf, preciso baixar este curso urgente, valeu

**Comment by fridafridex** [comment]
aparece esse erro que mencionei acima mas o processo continua, quando termina, o curso não está completo e com falhas na imagem e sem áudio, além de criar uma pasta [nome do curso] . json

**Comment by Kartatz** [comment]
Entre em contato comigo através do e-mail em luissilvaferreira@protonmail.com para que discutamos o problema mais afundo.
