### ISSUE TITLE
data7 academy

### ISSUE THREAD

**Issue by azforum** [Kartatz/SparkleC#65]
tentei baixa um curso do cursos data7 academy, que é vendido pela hotmart, mas não baixa, quando termino de add o usuario e senha, ele simplesmente fecha.

**Comment by Kartatz** [comment]
Execute o programa manualmente pelo PowerShell. Desse modo ele não irá fechar por conta própria.

Após isso, tente logar novamente na sua conta e envie uma captura de tela do erro que surge.

**Comment by azforum** [comment]
Olá.

Ele mostra a mensagem que não foi possível se conectar a URL.

Esse curso que estava tentando baixar, ele não está na plataforma Hormart e
em nenhuma das outras listadas no script, o curso foi só vendido na hotmart.

por isso ele não consegue fazer o download.

*Az Fórum | Atualizações Oficiais*
https://www.azforum.com.br/
*Brasil / Paraguai*
*para mais informações acesse o nosso grupo no Telegram*
https://t.me/azforum_oficial



Em sex., 1 de set. de 2023 às 21:25, Kartatz ***@***.***>
escreveu:

**Comment by Kartatz** [comment]
Sua descrição ainda é vaga. Como citei anteriormente, realize uma captura de tela (imagem) do erro e envie aqui.

**Comment by azforum** [comment]
Olá, viajei, por isso não respondi antes.

 Abaixo estão todas as URL no qual o script pode baixar os cursos.
1.
Nome: Hotmart
URL: https://hotmart.com

2.
Nome: Estratégia Concursos
URL: https://estrategiaconcursos.com.br

3.
Nome: Estratégia Vestibulares
URL: https://vestibulares.estrategia.com

4.
Nome: Estratégia Militares
URL: https://militares.estrategia.com

5.
Nome: IA Expert Academy
URL: https://iaexpert.academy

6.
Nome: Kiwify
URL: https://kiwify.com.br

No início , eu achei que os cursos que quero baixa estavam no hotmart, pois
comprei lá.
mas esses cursos não estão na plataforma hotmart, e sim em outra
plataforma, acredito que uma plataforma própria.

esse é o link de onde está os cursos
https://cursos.data7academy.com.br/

mesmo que eu tente com qualquer uma das url do script ele mostra o erro
Ocorreu uma falha inesperada ao tentar conectar com o servidor HTTP: The
requested URL returned error: 401

teria como adicionar ao script o site  data7academy ?

*Az Fórum | Atualizações Oficiais*
https://www.azforum.com.br/
*Brasil / Paraguai*
*para mais informações acesse o nosso grupo no Telegram*
https://t.me/azforum_oficial



Em qui., 7 de set. de 2023 às 11:26, Kartatz ***@***.***>
escreveu:

**Comment by Kartatz** [comment]
Entre em contato comigo [via e-mail](mailto:luissilvaferreira@protonmail.com) para discutirmos essa posibilidade.
