### ISSUE TITLE
Falha do script

### ISSUE THREAD

**Issue by CassioPaz66** [Kartatz/SparkleC#9]
Boa noite

O script sparkle está apresentando falha
Na versão anterior a mensagem é a que segue:
"- Sua sessão expirou ou foi revogada, refaça o login!"

Com a versão atualizada [x86_64-w64-mingw32.zip]
A mensagem alterou para:
"- Não foi possível realizar um login: A requisição para um servidor HTTP não pôde ser completada com êxito"

Refiz login e inclusive mudei senha, mas não encontro a falha.

Tenho curso em andamento que gostaria de fazer copia e se possível até mesmo compartilhar.

**Comment by Kartatz** [comment]
Baixe o aplicativo da Hotmart para Android e tente fazer o login através nele. Se não conseguir, significa que há algo de errado com a sua conta.

O SparkleC imita o comportamento do aplicativo. Então qualquer problema de login que você venha a enfrentar com o programa, muito provavelmente também será encontrado com o aplicativo oficial.

**Comment by CassioPaz66** [comment]
Boa noite Kartatz

Consegui baixar parcialmente o curso.
No meu caso toda vez que preciso baixar tenho que iniciar com opção "0" para entra com email e na sequencia a senha, pois numa segunda tentativa aparece o erro "- Sua sessão expirou ou foi revogada, refaça o login!".
Mas, alguns videos não foram baixados, simplesmente parou.

Fiz uma tentativa usando o Firefox e o pluin [downloadhelper], mas quando chega na mesma posição o download não continua e volta um erro.

Oque poderia ser ??

Valeu pela ajuda

**Comment by Kartatz** [comment]
Sem nenhuma captura de tela ou um registro da execução do programa fica um tanto quanto difícil descobrir algo, não acha?

Faça o que você deveria ter feito desde o início e envie-me uma dessas duas coisas.

**Comment by marcelostj** [comment]
Boa tarde, segue o erro que estou tendo, sempre que rodo o script ele para ai, tanto com nome completo quanto quando coloco nome aleatório: 
![image](https://user-images.githubusercontent.com/50970805/206264405-bef3a29c-589d-4ac9-aefa-1bb3c77a7dac.png)

**Comment by CassioPaz66** [comment]
Bom dia Kartatz

Segue um print da falha que comentei. Aproveitei recorte do print pois apresenta o mesmo problema.

Esse print lhe foi enviado por outro colega {Marcelo Silva Teixeira Junior} que está com o mesmo problema.

![Capturar](https://user-images.githubusercontent.com/57300935/206361691-167a5984-9782-4cca-b1d2-97a829de8db2.PNG)

**Comment by CassioPaz66** [comment]
Boa noite Kartatz

Obrigado pelo suporte.
E parabéns pelo desenvolvimento do programa.
Segui sua orientação com relação ao problema estar no tamanho dos nomes dos arquivos.
Desta feita, não optando por "não manter o nome original" todo o curso foi baixado.

Valeu pela ajuda e paciência.
